use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

use texpilot::compiler::{BibMode, BuildOptions, DraftPrepass, Engine, Runner, build};

const BIB2GLS_DOC: &str = r#"\documentclass{article}
\usepackage[record,style=index]{glossaries-extra}
\GlsXtrLoadResources[src={terms}]
\begin{document}
Use \gls{sample}.
\printunsrtglossary
\end{document}
"#;

const TERMS_BIB: &str = r#"@entry{sample,
  name = {Sample term},
  description = {A generated glossary entry}
}
"#;

#[test]
#[cfg(unix)]
fn direct_runner_builds_and_caches_bib2gls_resources() {
    if !command_available("pdflatex") || !tex_file_available("glossaries-extra.sty") {
        eprintln!("skipping Bib2Gls test; pdflatex or glossaries-extra.sty is unavailable");
        return;
    }

    let root = unique_temp_dir("texpilot-bib2gls-test");
    fs::create_dir_all(&root).expect("failed to create test directory");
    let main = root.join("main.tex");
    let terms = root.join("terms.bib");
    let out_dir = root.join("out");
    let fake_bin = root.join("bin");
    fs::create_dir_all(&fake_bin).expect("failed to create fake bin directory");
    write_fake_bib2gls(&fake_bin.join("bib2gls"));
    let _path_guard = PathGuard::prepend(&fake_bin);

    fs::write(&main, BIB2GLS_DOC).expect("failed to write Bib2Gls document");
    fs::write(&terms, TERMS_BIB).expect("failed to write Bib2Gls resource");

    let first = build(&options(&main, &out_dir)).expect("initial Bib2Gls build failed");
    assert_eq!(first.external_runs, 1, "{first:#?}");
    assert_eq!(first.tex_runs, 2, "{first:#?}");
    assert!(out_dir.join("main.pdf").exists());
    assert!(out_dir.join("main.glstex").exists());
    let log = fs::read_to_string(out_dir.join("main.log")).expect("failed to read TeX log");
    assert!(!log.contains("No file `main.glstex'"), "{log}");
    assert_eq!(fake_invocations(&out_dir), 1);

    let cached = build(&options(&main, &out_dir)).expect("cached Bib2Gls build failed");
    assert!(cached.skipped, "{cached:#?}");
    assert_eq!(cached.external_runs, 0, "{cached:#?}");
    assert_eq!(fake_invocations(&out_dir), 1);

    fs::write(
        &terms,
        format!("{TERMS_BIB}\n% resource edit that leaves fake output unchanged\n"),
    )
    .expect("failed to update Bib2Gls resource");
    let resource_edit = build(&options(&main, &out_dir)).expect("Bib2Gls resource edit failed");
    assert_eq!(resource_edit.external_runs, 1, "{resource_edit:#?}");
    assert_eq!(resource_edit.tex_runs, 0, "{resource_edit:#?}");
    assert!(resource_edit.aux_preflight_used, "{resource_edit:#?}");
    assert_eq!(fake_invocations(&out_dir), 2);

    let _ = fs::remove_dir_all(root);
}

#[cfg(unix)]
fn write_fake_bib2gls(path: &Path) {
    use std::os::unix::fs::PermissionsExt;

    fs::write(
        path,
        r#"#!/bin/sh
set -eu
job=""
for arg in "$@"; do
  job="$arg"
done
printf '%s\n' "$*" >> bib2gls.invocations
cat > "${job}.glstex" <<'GLSTEX'
\newglossaryentry{sample}{name={Sample term},description={Generated by fake bib2gls}}
GLSTEX
"#,
    )
    .expect("failed to write fake bib2gls");
    let mut permissions = fs::metadata(path)
        .expect("failed to stat fake bib2gls")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions).expect("failed to chmod fake bib2gls");
}

fn options(main: &Path, out_dir: &Path) -> BuildOptions {
    BuildOptions {
        main: main.to_path_buf(),
        job_name: None,
        engine: Engine::PdfLatex,
        runner: Runner::Direct,
        bib_mode: BibMode::Auto,
        out_dir: out_dir.to_path_buf(),
        fast: false,
        draft_prepass: DraftPrepass::Never,
        once: false,
        max_runs: 8,
        force: false,
        precompile_preamble: false,
        synctex: false,
        shell_escape: false,
        quiet: true,
        print_command: false,
    }
}

fn fake_invocations(out_dir: &Path) -> usize {
    fs::read_to_string(out_dir.join("bib2gls.invocations"))
        .map(|source| source.lines().count())
        .unwrap_or(0)
}

fn command_available(program: &str) -> bool {
    std::env::var_os("PATH")
        .map(|paths| {
            std::env::split_paths(&paths).any(|directory| directory.join(program).is_file())
        })
        .unwrap_or(false)
}

fn tex_file_available(name: &str) -> bool {
    std::process::Command::new("kpsewhich")
        .arg(name)
        .status()
        .is_ok_and(|status| status.success())
}

fn unique_temp_dir(prefix: &str) -> PathBuf {
    let unique = format!(
        "{}-{}-{}",
        prefix,
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system clock before UNIX epoch")
            .as_nanos()
    );
    std::env::temp_dir().join(unique)
}

#[cfg(unix)]
struct PathGuard {
    previous: Option<OsString>,
}

#[cfg(unix)]
impl PathGuard {
    fn prepend(directory: &Path) -> Self {
        let previous = std::env::var_os("PATH");
        let mut paths = vec![directory.to_path_buf()];
        if let Some(previous_paths) = previous.as_ref() {
            paths.extend(std::env::split_paths(previous_paths));
        }
        let joined = std::env::join_paths(paths).expect("failed to join PATH");
        unsafe {
            std::env::set_var("PATH", joined);
        }
        Self { previous }
    }
}

#[cfg(unix)]
impl Drop for PathGuard {
    fn drop(&mut self) {
        unsafe {
            if let Some(previous) = &self.previous {
                std::env::set_var("PATH", previous);
            } else {
                std::env::remove_var("PATH");
            }
        }
    }
}
